// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAraEASgoemS_CS0KODD1oUbnDPgf8GwyA',
    appId: '1:1092264039547:web:1c9ca9e10931ca86f93ede',
    messagingSenderId: '1092264039547',
    projectId: 'agpj-1faf2',
    authDomain: 'agpj-1faf2.firebaseapp.com',
    storageBucket: 'agpj-1faf2.firebasestorage.app',
    measurementId: 'G-95SES35J46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZJlfwkVSIhmisOhdXQ08A4Mpf4kRtBzE',
    appId: '1:1092264039547:android:20e7a9c215512e1cf93ede',
    messagingSenderId: '1092264039547',
    projectId: 'agpj-1faf2',
    storageBucket: 'agpj-1faf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnYpPsyeA_96I5UEfqIdsI1rdqG6LJa-8',
    appId: '1:1092264039547:ios:dd07698bc7fc0995f93ede',
    messagingSenderId: '1092264039547',
    projectId: 'agpj-1faf2',
    storageBucket: 'agpj-1faf2.firebasestorage.app',
    iosBundleId: 'com.example.agpj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnYpPsyeA_96I5UEfqIdsI1rdqG6LJa-8',
    appId: '1:1092264039547:ios:dd07698bc7fc0995f93ede',
    messagingSenderId: '1092264039547',
    projectId: 'agpj-1faf2',
    storageBucket: 'agpj-1faf2.firebasestorage.app',
    iosBundleId: 'com.example.agpj',
  );
}
